### PR TITLE
add different flavors for googleplay and appcenter

### PR DESCRIPTION
**Pull request by samarLavaloon**

### CODE REVIEW

**Comment by samarLavaloon** [comment]
Google Play considers the in-app update code as malicious behavior even if it isn’t used at runtime. Failure to not remove the in-app update code can lead to noncompliance and removal of the app from Google Play. So this pull request remove in-app updates for Google Play builds by creating two flavors foe appCenter and googlePlay. The steps included in the following link https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#remove-in-app-updates-for-google-play-builds

**Comment by samarLavaloon** [comment]
@hanabi1224 According to Google Play new Policy "in-app updates" need to be removed before October 16, 2020. After this date, Google Play will begin enforcing this new policy and could remove apps that violate it.

**Review by luizvnegrini — APPROVED** [review]

**Comment by luizvnegrini** [comment]
this PR will update the sdk version hehe, thanks!

**Comment by fadulalla** [comment]
Already approved, nice! When can we expect this to be merged?
I'm about to publish an update to my app and currently on the fence on whether to remove appcenter altogether or just wait for this PR!

Thanks both!

**Comment by Mardaneus86** [comment]
@hanabi1224 any chance to update the package on pub.dev to include this? Currently pub.dev has version `3.2.0+2`, last updated on July 24 2020.

**Comment by rockgecko-development** [comment]
Could the documentation please be updated, as I'm not sure how to use this? I'm familiar with flavors in projects, but unsure how to refer to ones defined in libraries - or how to use it with my app's existing flavors. Here's my current build.gradle:

```
flavorDimensions "app"
    productFlavors{
        dev{
            dimension "app"
            signingConfig signingConfigs.dev
            applicationId "com.myapp.dev"            
        }
        uat{
            dimension "app"
            signingConfig signingConfigs.uat
            applicationId "com.myapp.uat"            
        }
        prod{
            dimension "app"
            signingConfig signingConfigs.prod
            applicationId "com.myapp"            
        }
    }
```
I have `flutter build apk --flavor $BUILD_FLAVOR --$BUILD_TYPE` in my `appcenter-post-clone.sh`. I have 3 different builds configured in appcenter, and pass in a different BUILD_FLAVOR environment variable for each.

I'm just unsure how to add this other dimension.

**Pull request merged**
